services:
  musicweb:
    image: musicweb-image
    build:
      context: .
      dockerfile: MusicWeb/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Postgres=Host=db;Database=music;Username=music;Password=music
      - Redis__ConnectionString=redis:6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: postgres:15
    volumes:
      - db_data:/data
    environment:
      POSTGRES_USER: music
      POSTGRES_PASSWORD: music
      POSTGRES_DB: music

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U music -d music"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  liquibase:
    image: liquibase/liquibase:4.27
    volumes:
      - ./liquibase:/liquibase/changelog
    environment:
      - INSTALL_POSTGRESQL=false
      - LIQUIBASE_COMMAND_CHANGELOG_FILE=changelog/changelog.xml
      - LIQUIBASE_COMMAND_URL=jdbc:postgresql://db:5432/music
      - LIQUIBASE_COMMAND_USERNAME=music
      - LIQUIBASE_COMMAND_PASSWORD=music
      - LIQUIBASE_LOG_LEVEL=INFO
    command: update
    depends_on:
      db:
        condition: service_healthy

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./MusicWeb/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  redis_data:
  db_data:  